### ISSUE TITLE
请问该项目支持中文吗?

### ISSUE THREAD

**Issue by fastcode3d** [cnlinxi/style-token_tacotron2#1]
请问该项目原生支持中文吗?
还是说需要进行一些特殊的预处理步骤?
我看代码里是有支持中文的,utils里还有标贝数据

**Comment by cnlinxi** [comment]
这个项目实际上就是在THCHS-30上做的实验，本来就是中文合成TTS的，但是我没写使用文档。

**Comment by fastcode3d** [comment]
有空的话能写个简单的文档吗?
在中文上的效果如何?我也在做tacotron方面的中文工作,中文版的tacotron没什么问题,目前想在此基础上做声音风格转换,所以想参考这个项目.

**Comment by cnlinxi** [comment]
我已经更新了readme，你可以按照使用方法重现我的结果。抱歉这几天有点忙，如果还有问题可以继续讨论。
