### ISSUE TITLE
python preprocess.py

### ISSUE THREAD

**Issue by caopan16** [cnlinxi/style-token_tacotron2#2]
Hi, I run the commend "python preprocess.py",￼￼￼ it occurs the following error:
[luban@b8aeb1e5e498 style-token_tacotron2]$ python preprocess.py 
initializing preprocessing..
Selecting data folders..
0it [00:00, ?it/s]
Write 0 utterances, 0 mel frames, 0 audio timesteps, (0.00 hours)
Traceback (most recent call last):
  File "preprocess.py", line 142, in <module>
    main()
  File "preprocess.py", line 138, in main
    run_preprocess(args, modified_hp)
  File "preprocess.py", line 114, in run_preprocess
    preprocess(args, input_folders, output_folder, hparams)
  File "preprocess.py", line 38, in preprocess
    write_metadata(metadata, out_dir)
  File "preprocess.py", line 51, in write_metadata
    print('Max input length (text chars): {}'.format(max(len(m[5]) for m in metadata)))
ValueError: max() arg is an empty sequence

 I don't how to fix it, I am looking forward to get your reply. My project structure is as follows.

 LICENSE
-rw-r--r-- 1 luban deepmap      10348 May 11 11:53 README.md
drwxr-xr-x 1 luban deepmap        152 May 11 13:06 __pycache__
drwxr-xr-x 1 luban deepmap        216 Dec 30  2015 data_thchs30
-rw-r--r-- 1 luban deepmap 6453425169 May 11 14:44 data_thchs30.tgz
drwxr-xr-x 1 luban deepmap        272 May 11 16:32 datasets
-rw-r--r-- 1 luban deepmap       4521 May 11 11:53 griffin_lim_synthesis_tool.ipynb
-rw-r--r-- 1 luban deepmap      25976 May 11 11:53 hparams.py
-rw-r--r-- 1 luban deepmap       1231 May 11 11:53 infolog.py
-rw-r--r-- 1 luban deepmap       5851 May 11 16:33 preprocess.py
-rw-r--r-- 1 luban deepmap        191 May 11 11:53 requirements.txt
-rw-r--r-- 1 luban deepmap       4653 May 11 11:53 synthesize.py
drwxr-xr-x 1 luban deepmap        248 May 11 11:53 tacotron
-rw-r--r-- 1 luban deepmap       3555 May 11 11:53 test_wavenet_feeder.py
-rw-r--r-- 1 luban deepmap       5811 May 11 11:53 train.py
drwxr-xr-x 1 luban deepmap        216 May 11 15:11 training_data
drwxr-xr-x 1 luban deepmap        640 May 11 11:53 utils
-rw-r--r-- 1 luban deepmap       1867 May 11 11:53 wavenet_preprocess.py
drwxr-xr-x 1 luban deepmap        276 May 11 13:06 wavenet_vocoder

**Comment by cnlinxi** [comment]
I'm sorry to reply so late.
Please unzip data_thchs30
data_thchs30 should be a folder instead of file. There are data folder under this data_thchs30.

data_thchs30
---data
------\*.wav
------\*.trn

**Comment by caopan16** [comment]
thanks ,I have already unziped data_thchs30 , there are *.wav and *.trn in data folder. it doesn't work.

 I tar xvzf data_thchs30.tgz ,there the following folders in data_thchs30:
[luban@b8aeb1e5e498 data_thchs30]$ ll
total 2388
-rw-r--r-- 1 luban deepmap    1875 Dec 30  2015 README.TXT
drwxr-xr-x 1 luban deepmap 2097152 Dec 30  2015 data
drwxr-xr-x 1 luban deepmap   65536 Dec 30  2015 dev
drwxr-xr-x 1 luban deepmap     148 Jan 29  2016 lm_phone
drwxr-xr-x 1 luban deepmap     116 Jan 29  2016 lm_word
drwxr-xr-x 1 luban deepmap  262144 Dec 30  2015 test
drwxr-xr-x 1 luban deepmap 1048576 Dec 30  2015 train
in data folder:
[luban@b8aeb1e5e498 thchs30]$ cd data/
[luban@b8aeb1e5e498 data]$ ll
total 3923368
-r-xr-x--- 1 luban deepmap 249644 Dec 30  2015 A11_0.wav
-rw-r--r-- 1 luban deepmap    451 Dec 30  2015 A11_0.wav.trn
-r-xr-x--- 1 luban deepmap 282924 Dec 30  2015 A11_1.wav
-rw-r--r-- 1 luban deepmap    508 Dec 30  2015 A11_1.wav.trn
.......
it doesn't work , I don't how to solve it .

**Comment by cnlinxi** [comment]
Remain error: print('Max input length (text chars): {}'.format(max(len(m[5]) for m in metadata)))?
Please get new code, I update it today. Or you can copy datasets/preprocessor.py to replace the old one.
Because I modify THCHS-30 dataset, so the suffix of text file is '\*.trn2' instead of '\*.trn'
