### ISSUE TITLE
input the same text but output different 

### ISSUE THREAD

**Issue by kanatazhan** [cnlinxi/style-token_tacotron2#7]
Thanks for you work, and when I synthesize audio with the same text, I found that the outputs sound a little different, so I checked the inference from session.run and found that the same input leader to different output. Do you know why that happen?

**Comment by cnlinxi** [comment]
I donot know what do you mean. You should run `python synthesize.py --text_list <your corpus file> --name <your model name>`. If sentence in <your corpus file> is different, the synthesized voice is different.
