### ISSUE TITLE
训练好的模型load下来的时候失败?求大佬指点

### ISSUE THREAD

**Issue by 15755841658** [cnlinxi/style-token_tacotron2#8]
(wtx-style) cad-1@cad1-SYS-7048GR-TR:~/style-token_tacotron$ python synthesize.py --checkpoint logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-165000
all symbols is: ['_', '~', 'a', 'b', 'c', 'd', 'e', 'f', 'g', 'h', 'i', 'j', 'k', 'l', 'm', 'n', 'o', 'p', 'q', 'r', 's', 't', 'u', 'v', 'w', 'x', 'y', 'z', '1', '2', '3', '4', '5', '，', '。', '？', '，'！', '-', ' ']
Using TensorFlow backend.
Running End-to-End TTS Evaluation. Model: Tacotron-2
Synthesizing mel-spectrograms from text..
Traceback (most recent call last):
  File "/home/cad-1/style-token_tacotron/tacotron/synthesize.py", line 121, in tacotron_synthesize
    checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path
AttributeError: 'NoneType' object has no attribute 'model_checkpoint_path'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "synthesize.py", line 103, in <module>
    main()
  File "synthesize.py", line 97, in main
    synthesize(args, hparams, taco_checkpoint, wave_checkpoint, sentences)
  File "synthesize.py", line 38, in synthesize
    wavenet_in_dir = tacotron_synthesize(args, hparams, taco_checkpoint, sentences)
  File "/home/cad-1/style-token_tacotron/tacotron/synthesize.py", line 124, in tacotron_synthesize
    raise RuntimeError('Failed to load checkpoint at {}'.format(checkpoint))
RuntimeError: Failed to load checkpoint at logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-165000

**Comment by cnlinxi** [comment]
你好，你的目录有checkpoint文件嘛？
麻烦查看下logs-Tacotron-2/taco_pretrained/目录下文件有哪些？确保是完整的

**Comment by 15755841658** [comment]
是完整的,你看看
![Screenshot from 2019-12-18 17-51-57](https://user-images.githubusercontent.com/45281733/71075565-3c28d300-21bf-11ea-8de7-0e1e1a38ec39.png)

**Comment by cnlinxi** [comment]
不是吧，你这些ckpt文件没有修改过嘛，麻烦你能打开checkpoint看一下嘛～

**Comment by 15755841658** [comment]
![Screenshot from 2019-12-18 19-44-43](https://user-images.githubusercontent.com/45281733/71083828-e5c39080-21ce-11ea-8fd0-1d2bcb2e8c23.png)
这样?

**Comment by 15755841658** [comment]
![Screenshot from 2019-12-18 19-44-43](https://user-images.githubusercontent.com/45281733/71083859-f83dca00-21ce-11ea-8bf0-cbd6cb3873f2.png)

**Comment by cnlinxi** [comment]
这确实有些奇怪:(
你在执行`checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path`时，tensorflow应该去指定目录下寻找model_checkpoint_path，你的checkpoint文件明明指定的是380k step的checkpoint文件，它却去找到了165k step的checkpoint文件，但是165k step的checkpoint文件却没有在该文件中指明。
你可以尝试直接到tacotron/synthesize.py的126行修改：
`
checkpoint_path = tf.train.get_checkpoint_state(checkpoint).model_checkpoint_path
`
为：
`
checkpoint_path = 'logs-Tacotron-2/taco_pretrained/tacotron_model.ckpt-380000'
`

**Comment by cnlinxi** [comment]
feel free to reopen this issue:)
